version: '3.6'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__SAMPLE_VARIABLE="http://www.example.com"
    ports:
      - "5000:80"
      - "5001:443"
